version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ovu_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ovu_transport

  redis:
    image: redis:7-alpine
    container_name: ovu_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: ovu_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py

volumes:
  mongodb_data:
